### ISSUE TITLE
Add Backup Camera

### ISSUE THREAD

**Issue by HagenRankin** [GET-RAHS/2022-2024_Sockeye#2]
- [x] Write Code
- [x] Design Camera Mount
- [x] Design Screen Mount
- [x] Install Camera/Screen

**Comment by Jdaleigh** [comment]
Did you finish the camera mount Marcel?

**Comment by Orange-Duster** [comment]
i finished it back in december/january, but i want to improve it. shouldnt take long. screen mount will be done by thursday probably
