### ISSUE TITLE
Booster Seats

### ISSUE THREAD

**Issue by HagenRankin** [GET-RAHS/2022-2024_Sockeye#5]
- [ ] Find how many booster seats we need and what sizes
- [ ] Design 
- [ ] Build 
- [ ] Test

**Comment by MatthewF0ng** [comment]
1. Booster seats should be made with some form of rigid foam
2. Headspace must comply with head bar
3. Needs to allow the driver to laydown

**Comment by MatthewF0ng** [comment]
5.2.1	Safety Cell – All solar cars must be equipped with a safety cell that provides rigid protection encompassing the entire driver’s head, torso, legs, and feet. The purpose of the safety cell is to provide a solid structure that protects the driver and prevents intrusion of objects into the driver compartment.  The safety cell shall be a fixed, integral part of the solar car structure. The protection provided for the driver in a collision must be documented in the team's mechanical drawings. In addition to providing collision and rollover protection, the safety cell must be designed so as to deflect body/array panels of the car away from the driver in the event of an accident.  
5.2.1.1	Minimum Dimensions – The safety cell tubing must have a minimum outside diameter of 1.9 cm.  There must be at least 5 cm of clearance in all directions between the safety cell and the driver seated in the normal driving position.  Teams must demonstrate at scrutineering that each driver complies with the 5 cm clearance. 
5.2.1.2	Coverage – If the safety cell was to be wrapped in an elastic fabric, no part of the driver should touch the fabric. The arms may extend out of the safety cell when holding the steering wheel.
5.2.1.3	Padding – The safety cell, including the roll bar, must be padded with a high density padding wherever a driver may likely contact it in a collision (e.g. heads, knees, elbows).
5.2.2	Roll Bar – The roll bar is a distinct structural member that is a key part of the safety cell. The roll bar extends above the driver’s head, protecting the driver in the event of a roll-over.  The roll bar must consist of one continuous piece of metal.  The bottom of the roll bar must extend at least 5 cm vertically from the top of the driver’s head or helmet.

**Comment by MatthewF0ng** [comment]
Made the Small Booster seat, I need more foam and velcro

**Comment by MatthewF0ng** [comment]
Layering it with softer foam, need to add fabric to prevent erosion and find a better way to connect the velcro

**Comment by MatthewF0ng** [comment]
Add a bottom wooden piece or cut to the exact angle of the seat for tightening and security.
